### PR TITLE
Test-for-Subject

### PR DESCRIPTION
**Pull request by ngovannghiaframgia**
ready

### CODE REVIEW

**Comment by ngovannghiaframgia** [comment]
ready

**Comment by ngovannghiaframgia** [comment]
ready
screenshot from 2019-03-08 15-52-19

**Comment by ngovannghiaframgia** [comment]
ready

**Review by huongnguyenmta — COMMENTED** [review]
conflicted

**Comment by ngovannghiaframgia** [comment]
ready

**Pull request merged**
